engines:
  fixme:
    enabled: true

languages:
  CSS: true
  JavaScript: true
  Python: true

exclude_paths:
- poradnia/cases/static/cases/lou-multiselect/*
- poradnia/assets/js/jquery.formset.js
- poradnia/*/migrations/*
