engines:
  fixme:
    enabled: true

# Analysis settings for Languages and Engines are both valid but mutually exclusive.
# languages:
#  CSS: true
#  JavaScript: true
#  Python: true

exclude_paths:
- poradnia/cases/static/cases/lou-multiselect/*
- poradnia/assets/js/jquery.formset.js
- poradnia/*/migrations/*
