services:
- docker

env:
  global:
    - WEB_REPOSITORY_NAME="quay.io/watchdogpolska/poradnia-django"
    - DOCS_REPOSITORY_NAME="quay.io/watchdogpolska/poradnia-docs"
  matrix:
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=2.7

before_install:
  - echo "$DOCKER_PASSWORD" | docker login "quay.io" -u "$DOCKER_USERNAME" --password-stdin
  - . ./.contrib/travis/env.sh

install:
  - ./.contrib/travis/build.sh

script:
  - ./.contrib/travis/test.sh

deploy:
  provider: script
  script: ./.contrib/travis/deploy.sh
