language: python
env:
  - DATABASE_URL=mysql://travis:@localhost/
python:
  - "2.7"
env:
  - DJANGO=1.7.1
  - DJANGO=1.8
  - DJANGO=1.6
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install pip --upgrade
  - pip install -q Django==$DJANGO --cache-dir $HOME/.pip-cache
  - pip install pep8 --cache-dir $HOME/.pip-cache
  - pip install -r requirements/test.txt --cache-dir $HOME/.pip-cache
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128,E121 poradnia"
  - pyflakes -x W src
script:
  - python poradnia/manage.py test
